//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public int VesselsId { get; set; }
        public string VesselName { get; set; }
        public string Terminal { get; set; }
        public string Country { get; set; }
    }
}
